name: SimplScenes
options:
  bundleIdPrefix: com.sudobuiltapps
  deploymentTarget:
    tvOS: "17.0"
  indentWidth: 2

packages: {}

targets:
  SimplScenes:
    type: application
    platform: tvOS
    deploymentTarget: "17.0"
    bundleId: com.sudobuiltapps.simplscenes
    sources:
      - Sources/SimplScenes
    resources:
      - path: Resources
        buildPhase: resources
      - path: SimplScenes/StoreKit.storekit
        buildPhase: none
    settings:
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: 9G5Y8G34K5
      PRODUCT_BUNDLE_IDENTIFIER: com.sudobuiltapps.simplscenes
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      SDKROOT: appletvos
      TVOS_DEPLOYMENT_TARGET: "17.0"
      GENERATE_INFOPLIST_FILE: "YES"
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: SimplScenes
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        UIUserInterfaceStyle: Dark
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
    capabilities:
      - inAppPurchase

  SimplScenesTests:
    type: bundle.unit-test
    platform: tvOS
    deploymentTarget: "17.0"
    sources:
      - Tests/SimplScenesTests
    dependencies:
      - target: SimplScenes
    settings:
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: 9G5Y8G34K5
      GENERATE_INFOPLIST_FILE: "YES"

schemes:
  SimplScenes:
    build:
      targets:
        SimplScenes: all
        SimplScenesTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - SimplScenesTests
